FROM eclipse-temurin:11-jre-focal

COPY agent.tar /tmp/agent.tar
RUN tar -xf /tmp/agent.tar -C /opt && rm /tmp/agent.tar

RUN sed -i 's/agent.controller_host=.*/agent.controller_host=controller/' \
    /opt/ngrinder-agent/__agent.conf

CMD rm -f /root/.ngrinder_agent/pid.ngrinder && /opt/ngrinder-agent/run_agent.sh
